criterion:
  name: distanceLoss
  min_distance: 0.12

aux_criterion:
  aspect_ratio_loss:
    aspect_ratio: 0.1
    weight: 0
  curl_loss:
    weight: 0.0
  tv_loss:
    weight: 0.0
    norm: False
  maxwell_residual_loss:
    weight: 0.0
    wl_cen: 1.55
    wl_width: 0
    n_wl: 1
  grad_loss:
    weight: 0.0
  s_param_loss:
    weight: 0.0
  err_corr:
    weight: 0.0

test_criterion:
  name: mse

optimizer:
  name: adam
  lr: 0.1
  weight_decay: 0.000
  line_search_fn: None

lr_scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 1e-3

sharp_scheduler:
  name: sharpness
  init_sharp: 1
  final_sharp: 20
  sharp_threshold: 0.05

res_scheduler:
  name: resolution
  init_res: 20
  final_res: 20
  test_res: 20

run:
  experiment: "fno2d"
  n_epochs: 20
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  random_state: 42
  log_interval: 10
  fp16: False
  wandb:
    project: MAPS
    entity: scopex
    name: local_search

quantize:
  weight_bit: 32
  input_bit: 32

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "metacoupler/local_search/train_local_search"
  model_comment: ""
  resume: 0
  restore_checkpoint: ""
  no_linear: 0

model:
  name: FNO3d
  out_channels: 2
  dim: 32
  kernel_list: [64, 64, 64, 64, 64, 64]
  kernel_size_list: [1, 1, 1, 1, 1, 1]
  hidden_list: [64]
  padding_list: [0, 0, 0, 0, 0, 0]
  mode_list: [[80, 80]]
  act_func: GELU
  act_thres: 100
  dropout_rate: 0.1
  drop_path_rate: 0.2
  norm: bn
  aux_head: False
  aux_head_idx: 1
  pos_encoding: none
  with_cp: False
  in_channels: 3

debug:
  verbose: 1

plot:
  train: True
  valid: True
  test: True
  interval: 1
  phase_intensity_profile_interval: 5
  dir_name: local_search
  output_video: False
  solve_cw: False
